# Site settings
title: Rui Chicória
email: me@ruichicoria.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack developer. Open source enthusiast.
  Avid learner. Lead software engineer at Sentilant.
baseurl: "/myposts" # the subpath of your site, e.g. /blog/
url: "http://myposts.ruichicoria.com" # the base hostname & protocol for your site
twitter_username: rchicoria
github_username:  rchicoria

# Build settings
markdown: kramdown

safe: true
lsi: false
source: .
